version: "3.9"
services:

  cashflow:
    build:
        context: .
    volumes:
      - .:/app/www
    ports:
      - "8000:9501"
    networks:
      - docker-net

  redis:
    image: "redis:alpine"
    restart: always
    ports:
      - '6379:6379'
    volumes:
      - cache:/data
    networks:
      - docker-net

  phpredisadmin:
    image: "erikdubbelboer/phpredisadmin"
    environment:
      - ADMIN_USER=admin
      - ADMIN_PASS=admin
      - REDIS_1_HOST=redis
      - REDIS_1_PORT=6379
    networks:
      - docker-net
    ports:
      - "8080:80"
  
  postgres:
    image: postgres:alpine
    environment:
      POSTGRES_USER: ${POSTGRES_USER:-postgres}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-changeme}
      PGDATA: /data/postgres
    volumes:
       - postgres:/data/postgres
    ports:
      - "5432:5432"
    networks:
      - docker-net
    restart: unless-stopped

  pgadmin:
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL:-pgadmin4@pgadmin.org}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD:-admin}
      PGADMIN_CONFIG_SERVER_MODE: 'False'
    volumes:
       - pgadmin:/var/lib/pgadmin
    ports:
      - "${PGADMIN_PORT:-5050}:80"
    networks:
      - docker-net
    restart: unless-stopped
  
  # elasticsearch:
  #   container_name: es-container
  #   image: docker.elastic.co/elasticsearch/elasticsearch:8.4.0
  #   environment:
  #     - xpack.security.enabled=false
  #     - "discovery.type=single-node"
  #   networks:
  #     - docker-net
  #   ports:
  #     - 9200:9200

  # kibana:
  #   container_name: kb-container
  #   image: docker.elastic.co/kibana/kibana:8.4.0
  #   environment:
  #     - ELASTICSEARCH_HOSTS=http://es-container:9200
  #   networks:
  #     - docker-net
  #   depends_on:
  #     - elasticsearch
  #   ports:
  #     - 5601:5601

  # rabbitmq:
  #     image: rabbitmq:3-management-alpine
  #     container_name: rabbitmq
  #     environment:
  #         RABBITMQ_DEFAULT_USER: "guest"
  #         RABBITMQ_DEFAULT_PASS: "guest"
  #     ports:
  #         - 5672:5672
  #         - 15672:15672
          
networks:
  docker-net:
    driver: bridge

volumes:
  postgres:
  pgadmin:
  cache:
    driver: local
